# Generated by Django 2.2.6 on 2020-10-14 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogPostModule', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=20)),
                ('lastName', models.CharField(max_length=20)),
                ('Uemail', models.EmailField(max_length=254)),
                ('Reason', models.TextField(max_length=150)),
                ('isReplied', models.BooleanField(default=False)),
            ],
        ),
    ]
